# Author: Julian Bolivar
# Version: 1.0.0
# Date: 2026-08-25
"""Unit tests for the S11 scenario's own shape."""

import pathlib
import unittest

from smoke import runs
from smoke.outcome import Outcome
from smoke.product import ProductOutput
from smoke.registry import DEFAULT_REGISTRY
from smoke.scenarios import config_fatal  # noqa: F401 - import registers it
from smoke.tests import support

#: A configuration shaped like the one the product scaffolds: a root
#: ``base_url``, an ``[openai]`` table, and three seats each declaring a model
#: AND its lineage. The variants are built by editing this, so it has to carry
#: both halves of every seat or the edit under test has nothing to remove.
_GENERATED = """# Generated by magi init
provider = "ollama"
base_url = "http://localhost:11434/v1"

[openai]
model = "kimi-k2.6:cloud"

[magi]
melchior_model  = "a:cloud"
balthasar_model = "b:cloud"
caspar_model    = "c:cloud"
melchior_lineage  = "qwen"
balthasar_lineage = "gpt-oss"
caspar_lineage    = "deepseek"
"""


class _FakeProduct:
    """A product double that scaffolds, then refuses each broken variant.

    Attributes:
        seats_named: How many seats the missing-lineage refusal names.
        exit_code: What a rejected configuration exits with.
        reaches_backend: Whether the refusal carries a connection failure,
            which is what a run that issued a request before rejecting the
            configuration would look like.
    """

    def __init__(self, seats_named: int = 3,
                 exit_code: int = 2, reaches_backend: bool = False) -> None:
        """Create the double.

        Args:
            seats_named: How many of the three seats to name.
            exit_code: The code a rejected configuration exits with.
            reaches_backend: Emit a connection failure alongside the refusal.
        """
        self.seats_named = seats_named
        self.exit_code = exit_code
        self.reaches_backend = reaches_backend

    def __call__(self, call: support.Call) -> ProductOutput | None:
        """Answer one invocation.

        Args:
            call: What the fake binary was asked to run.

        Returns:
            ProductOutput: The canned answer, or None for the failed default.
        """
        root = pathlib.Path(call.cwd) if call.cwd else None
        if call.args[:1] == ("init",):
            return self._scaffold(root)
        if call.args[:1] != ("query",) or root is None:
            return None
        return self._reject(root)

    @staticmethod
    def _scaffold(root: pathlib.Path | None) -> ProductOutput:
        """Write a workspace the way ``magi init`` would.

        Args:
            root: Where to scaffold.

        Returns:
            ProductOutput: Exit 0, or exit 1 when there was nowhere to write.
        """
        if root is None:
            return _capture(b"", b"no working directory", 1)
        magi = root / ".magi"
        magi.mkdir(parents=True, exist_ok=True)
        (magi / "magi.toml").write_text(_GENERATED, encoding="utf-8")
        return _capture(b"", b"", 0)

    def _reject(self, root: pathlib.Path) -> ProductOutput:
        """Refuse whichever broken configuration is installed.

        Args:
            root: The workspace's parent directory.

        Returns:
            ProductOutput: The refusal the real product would print.
        """
        text = (root / ".magi" / "magi.toml").read_text(encoding="utf-8")
        if config_fatal.UNKNOWN_FIELD in text:
            message = "error: unknown field `%s`" % config_fatal.UNKNOWN_FIELD
        elif "tool_result_cap_bytes" in text:
            named = (config_fatal.V011_MARKERS if self.all_at_once
                     else config_fatal.V011_MARKERS[:1])
            message = "error: migrate: " + ", ".join(named)
        elif "_lineage" not in text:
            named = config_fatal.SEATS[:self.seats_named]
            message = "error: seats without a lineage: " + ", ".join(named)
        else:
            return _capture(b'{"response":"ok"}', b"", 0)
        if self.reaches_backend:
            message += "\nerror sending request: connection refused"
        return _capture(b"", message.encode("utf-8"), self.exit_code)


def _capture(stdout: bytes, stderr: bytes, exit_code: int) -> ProductOutput:
    """Build a canned capture.

    Args:
        stdout: What the product printed.
        stderr: What it wrote to the error stream.
        exit_code: The code it exited with.

    Returns:
        ProductOutput: The capture.
    """
    return ProductOutput(stdout=stdout, stderr=stderr, exit_code=exit_code,
                         command=["magi-rs", "query"])


def _outcomes() -> dict[str, Outcome]:
    """Run S11 against whatever double is installed, indexed by assertion.

    Returns:
        dict[str, Outcome]: What each assertion concluded.
    """
    findings = list(DEFAULT_REGISTRY.get("S11").func(None))
    return {finding.assertion: finding.outcome for finding in findings}


class ConfigFatalScenarioTests(unittest.TestCase):
    """S11 is registered standalone and declares its four assertions."""

    def test_s11_is_registered_without_a_run(self) -> None:
        entry = DEFAULT_REGISTRY.get("S11")
        self.assertIsNone(entry.run)
        self.assertFalse(entry.needs_backend)

    def test_the_assertion_texts_are_the_spec_texts(self) -> None:
        self.assertEqual(
            [
                "an unknown field in magi.toml exits 2 naming the field",
                "it cuts before any backend request is issued",
                "a seat declaring a model without its lineage fails naming all "
                "three seats",
            ],
            list(config_fatal.S11_ASSERTIONS),
        )


class ConfigFatalScenarioBodyTests(unittest.TestCase):
    """What S11 concludes about a product that refuses well, and badly."""

    def test_a_product_that_scaffolds_nothing_still_reports_them_all(self) -> None:
        support.install_fake_runs(self)
        findings = list(DEFAULT_REGISTRY.get("S11").func(None))
        self.assertEqual(list(config_fatal.S11_ASSERTIONS),
                         [finding.assertion for finding in findings])
        self.assertEqual({Outcome.CANNOT_TEST},
                         {finding.outcome for finding in findings})

    def test_a_product_that_refuses_well_passes_every_assertion(self) -> None:
        support.install_fake_runs(self, responder=_FakeProduct())
        self.assertEqual({Outcome.PASS},
                         set(_outcomes().values()))

    def test_naming_one_seat_of_three_fails(self) -> None:
        support.install_fake_runs(self, responder=_FakeProduct(seats_named=1))
        outcomes = _outcomes()
        self.assertEqual(Outcome.FAIL,
                         outcomes[config_fatal.S11_ASSERTIONS[2]])

    def test_a_refusal_that_first_contacted_the_backend_fails(self) -> None:
        support.install_fake_runs(self,
                                  responder=_FakeProduct(reaches_backend=True))
        outcomes = _outcomes()
        self.assertEqual(Outcome.FAIL,
                         outcomes[config_fatal.S11_ASSERTIONS[1]])

    def test_the_wrong_exit_code_fails_even_when_the_field_is_named(self) -> None:
        """Refusing and refusing usefully are different guarantees, and the
        operator needs the second one to script against.
        """
        support.install_fake_runs(self, responder=_FakeProduct(exit_code=1))
        outcomes = _outcomes()
        self.assertEqual(Outcome.FAIL,
                         outcomes[config_fatal.S11_ASSERTIONS[0]])

    def test_the_variants_are_written_under_the_scratch_area(self) -> None:
        """REQ-S30: the persistent environment's own configuration is never
        one of the variants, or a broken file would outlive the scenario.
        """
        binary = support.install_fake_runs(self, responder=_FakeProduct())
        list(DEFAULT_REGISTRY.get("S11").func(None))
        scratch = pathlib.Path(str(runs.scratch_root())).resolve()
        for call in binary.calls:
            if call.cwd is None:
                continue
            self.assertTrue(
                pathlib.Path(str(call.cwd)).resolve().is_relative_to(scratch),
                "S11 ran the product outside the scratch area: %s" % call.cwd,
            )


class _FakeEnvReader:
    """A product double that reads the environment the way the product does.

    Attributes:
        blank_is_invalid: Whether a blank value is treated as a present one and
            rejected against the vocabulary. That is the defect assertions 1
            and 2 exist to catch.
        every_value_is_absent: Whether even a filled-in unrecognised value
            falls through. That is the OPPOSITE defect -- the fix overshooting
            into accepting anything -- and only assertion 3 can see it.
    """

    def __init__(self, blank_is_invalid: bool = False,
                 every_value_is_absent: bool = False) -> None:
        """Create the double.

        Args:
            blank_is_invalid: Reject blank values against the vocabulary.
            every_value_is_absent: Never reject any value.
        """
        self.blank_is_invalid = blank_is_invalid
        self.every_value_is_absent = every_value_is_absent

    def __call__(self, call: support.Call) -> ProductOutput | None:
        """Answer one invocation.

        Args:
            call: What the fake binary was asked to run.

        Returns:
            ProductOutput: The canned answer, or None for the failed default.
        """
        if call.args[:1] == ("init",):
            return _FakeProduct._scaffold(
                pathlib.Path(call.cwd) if call.cwd else None)
        if call.args[:1] != ("query",):
            return None
        env = call.env or {}
        passphrase = env.get("MAGI_PASSPHRASE", support.FAKE_PASSPHRASE)
        if not passphrase.strip():
            return _capture(
                b"",
                b"error: no passphrase: use -p or MAGI_PASSPHRASE in "
                b"non-interactive environments\n", 1)
        provider = env.get("MAGI_PROVIDER", "")
        present = bool(provider.strip()) or (self.blank_is_invalid
                                             and "MAGI_PROVIDER" in env)
        known = provider.strip() in ("ollama", "openai-compat", "anthropic")
        if present and not known and not self.every_value_is_absent:
            return _capture(
                b"", b'error: unknown provider: "%s" (valid: ollama, '
                     b'openai-compat, anthropic)\n' % provider.encode("utf-8"),
                2)
        return _capture(b"", b"error sending request: connection refused\n", 1)


class BlankEnvScenarioTests(unittest.TestCase):
    """S15 is registered standalone and declares its three assertions."""

    def test_s15_is_registered_without_a_run(self) -> None:
        entry = DEFAULT_REGISTRY.get("S15")
        self.assertIsNone(entry.run)
        self.assertFalse(entry.needs_backend)

    def test_the_assertion_texts_are_the_spec_texts(self) -> None:
        self.assertEqual(
            [
                "each text-valued variable, exported empty or blank, falls "
                "through to the next precedence level",
                "startup succeeds — no vocabulary error, no empty credential "
                "short-circuiting the vault lookup",
                "a value that is present and unrecognised is still an error",
            ],
            list(config_fatal.S15_ASSERTIONS),
        )

    def test_every_variable_the_spec_names_is_covered(self) -> None:
        """The spec covers eight variables in one pass, so the scenario has to
        exercise eight. A shorter list is a smaller guarantee wearing the same
        assertion text.
        """
        self.assertEqual(8, len(config_fatal.BLANKABLE_VARIABLES))
        for name in ("MAGI_PROVIDER", "MAGI_PASSPHRASE", "OPENAI_BASE_URL",
                     "OPENAI_MODEL", "ANTHROPIC_MODEL", "ANTHROPIC_API_KEY",
                     "OPENAI_API_KEY"):
            self.assertIn(name, config_fatal.BLANKABLE_VARIABLES)
        self.assertTrue(
            any(name.startswith("MAGI_MODEL_")
                for name in config_fatal.BLANKABLE_VARIABLES),
            "the MAGI_MODEL_* family is not represented",
        )

    def test_both_spellings_of_blank_are_exercised(self) -> None:
        """An exported-but-unfilled variable in a CI script is the everyday
        accident this protects, and it arrives in both spellings.
        """
        self.assertEqual(("", "   "), config_fatal.BLANK_SPELLINGS)


class BlankEnvScenarioBodyTests(unittest.TestCase):
    """What S15 concludes about a product that reads blanks well, and badly."""

    def _outcomes(self) -> dict[str, Outcome]:
        """Run S15 and index its outcomes by assertion.

        Returns:
            dict[str, Outcome]: What each assertion concluded.
        """
        findings = list(DEFAULT_REGISTRY.get("S15").func(None))
        return {finding.assertion: finding.outcome for finding in findings}

    def test_a_product_that_scaffolds_nothing_still_reports_all_three(self) -> None:
        support.install_fake_runs(self)
        findings = list(DEFAULT_REGISTRY.get("S15").func(None))
        self.assertEqual(list(config_fatal.S15_ASSERTIONS),
                         [finding.assertion for finding in findings])
        self.assertEqual({Outcome.CANNOT_TEST},
                         {finding.outcome for finding in findings})

    def test_a_product_that_reads_blanks_as_absent_passes(self) -> None:
        support.install_fake_runs(self, responder=_FakeEnvReader())
        self.assertEqual({Outcome.PASS}, set(self._outcomes().values()))

    def test_a_blank_rejected_against_the_vocabulary_fails(self) -> None:
        support.install_fake_runs(
            self, responder=_FakeEnvReader(blank_is_invalid=True))
        outcomes = self._outcomes()
        self.assertEqual(Outcome.FAIL, outcomes[config_fatal.S15_ASSERTIONS[0]])
        self.assertEqual(Outcome.FAIL, outcomes[config_fatal.S15_ASSERTIONS[1]])

    def test_accepting_an_unrecognised_value_fails(self) -> None:
        """Without assertion 3 a product that treated EVERY value as absent
        would pass the first two perfectly, which is the fix overshooting.
        """
        support.install_fake_runs(
            self, responder=_FakeEnvReader(every_value_is_absent=True))
        outcomes = self._outcomes()
        self.assertEqual(Outcome.PASS, outcomes[config_fatal.S15_ASSERTIONS[0]])
        self.assertEqual(Outcome.FAIL, outcomes[config_fatal.S15_ASSERTIONS[2]])

    def test_the_passphrase_variable_is_bounded_not_awaited(self) -> None:
        """A blank MAGI_PASSPHRASE falls through to a TTY prompt that does not
        exist here, so the expected answer is the typed refusal. Every
        invocation carries a timeout, so a regression that hangs fails the
        scenario instead of the harness.
        """
        binary = support.install_fake_runs(self, responder=_FakeEnvReader())
        list(DEFAULT_REGISTRY.get("S15").func(None))
        blanked = [call for call in binary.calls
                   if (call.env or {}).get("MAGI_PASSPHRASE", "x").strip() == ""]
        self.assertTrue(blanked, "the passphrase was never blanked")
        for call in blanked:
            self.assertIsNotNone(call.timeout)


class BlankPassphraseTests(unittest.TestCase):
    """What the product actually contracts for a blank MAGI_PASSPHRASE."""

    def test_a_typed_refusal_at_exit_1_is_accepted_whichever_it_is(self) -> None:
        """The rule this scenario rests on ENUMERATES its variables, and the
        passphrase is not among them.

        ``CLAUDE.md``'s blank-is-absent rule names provider, kind,
        default_mode, base_url, the model resolvers, ``MAGI_MODEL_*`` and the
        two API keys. ``MAGI_PASSPHRASE`` has its own precedence -- flag, then
        environment, then a TTY prompt -- and nothing promises a blank one is
        read as absent. Requiring the "no passphrase" wording asserted a
        contract the product never published, and the product answers
        "incorrect passphrase": it tried the blank value, which is a defensible
        reading of "present".

        What IS promised, and what this checks, is that the refusal is typed
        and bounded: exit 1, a diagnosable message, never a hang.
        """
        output = ProductOutput(stdout=b"", stderr=b"error: incorrect passphrase",
                               exit_code=1, command=["magi-rs", "query"])
        self.assertEqual([], config_fatal._passphrase_complaints("   ", output))

    def test_an_untyped_message_is_a_complaint_even_at_exit_1(self) -> None:
        """Isolated to the WORDING check, deliberately.

        A fixture that also carried a wrong exit code would be caught by the
        exit check, and dropping the wording check would leave it green -- a
        test guarded by the branch it is not testing. Exit 1 here, so only the
        wording can catch it.
        """
        output = ProductOutput(stdout=b"", stderr=b"thread 'main' panicked",
                               exit_code=1, command=["magi-rs", "query"])
        self.assertNotEqual([], config_fatal._passphrase_complaints("   ", output))

    def test_a_typed_refusal_at_the_wrong_exit_code_is_a_complaint(self) -> None:
        """The mirror, isolated to the EXIT check: the wording is right, so
        only the code can catch it. A refusal that exits 101 is a crash wearing
        a refusal's message, and a CI reading the code cannot tell.
        """
        output = ProductOutput(stdout=b"", stderr=b"error: incorrect passphrase",
                               exit_code=101, command=["magi-rs", "query"])
        self.assertNotEqual([], config_fatal._passphrase_complaints("   ", output))


if __name__ == "__main__":
    unittest.main()
