# Author: Julian Bolivar
# Version: 1.0.0
# Date: 2026-08-25
"""Unit tests for the S11 scenario's own shape."""

import pathlib
import unittest

from smoke import runs
from smoke.outcome import Outcome
from smoke.product import ProductOutput
from smoke.registry import DEFAULT_REGISTRY
from smoke.scenarios import config_fatal  # noqa: F401 - import registers it
from smoke.tests import support

#: A configuration shaped like the one the product scaffolds: a root
#: ``base_url``, an ``[openai]`` table, and three seats each declaring a model
#: AND its lineage. The variants are built by editing this, so it has to carry
#: both halves of every seat or the edit under test has nothing to remove.
_GENERATED = """# Generated by magi init
provider = "ollama"
base_url = "http://localhost:11434/v1"

[openai]
model = "kimi-k2.6:cloud"

[magi]
melchior_model  = "a:cloud"
balthasar_model = "b:cloud"
caspar_model    = "c:cloud"
melchior_lineage  = "qwen"
balthasar_lineage = "gpt-oss"
caspar_lineage    = "deepseek"
"""


class _FakeProduct:
    """A product double that scaffolds, then refuses each broken variant.

    Attributes:
        all_at_once: Whether the v0.11.0-era file is reported whole or one
            incompatibility at a time.
        seats_named: How many seats the missing-lineage refusal names.
        exit_code: What a rejected configuration exits with.
        reaches_backend: Whether the refusal carries a connection failure,
            which is what a run that issued a request before rejecting the
            configuration would look like.
    """

    def __init__(self, all_at_once: bool = True, seats_named: int = 3,
                 exit_code: int = 2, reaches_backend: bool = False) -> None:
        """Create the double.

        Args:
            all_at_once: Report every v0.11.0 incompatibility together.
            seats_named: How many of the three seats to name.
            exit_code: The code a rejected configuration exits with.
            reaches_backend: Emit a connection failure alongside the refusal.
        """
        self.all_at_once = all_at_once
        self.seats_named = seats_named
        self.exit_code = exit_code
        self.reaches_backend = reaches_backend

    def __call__(self, call: support.Call) -> ProductOutput | None:
        """Answer one invocation.

        Args:
            call: What the fake binary was asked to run.

        Returns:
            ProductOutput: The canned answer, or None for the failed default.
        """
        root = pathlib.Path(call.cwd) if call.cwd else None
        if call.args[:1] == ("init",):
            return self._scaffold(root)
        if call.args[:1] != ("query",) or root is None:
            return None
        return self._reject(root)

    @staticmethod
    def _scaffold(root: pathlib.Path | None) -> ProductOutput:
        """Write a workspace the way ``magi init`` would.

        Args:
            root: Where to scaffold.

        Returns:
            ProductOutput: Exit 0, or exit 1 when there was nowhere to write.
        """
        if root is None:
            return _capture(b"", b"no working directory", 1)
        magi = root / ".magi"
        magi.mkdir(parents=True, exist_ok=True)
        (magi / "magi.toml").write_text(_GENERATED, encoding="utf-8")
        return _capture(b"", b"", 0)

    def _reject(self, root: pathlib.Path) -> ProductOutput:
        """Refuse whichever broken configuration is installed.

        Args:
            root: The workspace's parent directory.

        Returns:
            ProductOutput: The refusal the real product would print.
        """
        text = (root / ".magi" / "magi.toml").read_text(encoding="utf-8")
        if config_fatal.UNKNOWN_FIELD in text:
            message = "error: unknown field `%s`" % config_fatal.UNKNOWN_FIELD
        elif "tool_result_cap_bytes" in text:
            named = (config_fatal.V011_MARKERS if self.all_at_once
                     else config_fatal.V011_MARKERS[:1])
            message = "error: migrate: " + ", ".join(named)
        elif "_lineage" not in text:
            named = config_fatal.SEATS[:self.seats_named]
            message = "error: seats without a lineage: " + ", ".join(named)
        else:
            return _capture(b'{"response":"ok"}', b"", 0)
        if self.reaches_backend:
            message += "\nerror sending request: connection refused"
        return _capture(b"", message.encode("utf-8"), self.exit_code)


def _capture(stdout: bytes, stderr: bytes, exit_code: int) -> ProductOutput:
    """Build a canned capture.

    Args:
        stdout: What the product printed.
        stderr: What it wrote to the error stream.
        exit_code: The code it exited with.

    Returns:
        ProductOutput: The capture.
    """
    return ProductOutput(stdout=stdout, stderr=stderr, exit_code=exit_code,
                         command=["magi-rs", "query"])


def _outcomes() -> dict[str, Outcome]:
    """Run S11 against whatever double is installed, indexed by assertion.

    Returns:
        dict[str, Outcome]: What each assertion concluded.
    """
    findings = list(DEFAULT_REGISTRY.get("S11").func(None))
    return {finding.assertion: finding.outcome for finding in findings}


class ConfigFatalScenarioTests(unittest.TestCase):
    """S11 is registered standalone and declares its four assertions."""

    def test_s11_is_registered_without_a_run(self) -> None:
        entry = DEFAULT_REGISTRY.get("S11")
        self.assertIsNone(entry.run)
        self.assertFalse(entry.needs_backend)

    def test_the_assertion_texts_are_the_spec_texts(self) -> None:
        self.assertEqual(
            [
                "an unknown field in magi.toml exits 2 naming the field",
                "it cuts before any backend request is issued",
                "a v0.11.0-era file names every incompatibility at once, not "
                "just the first",
                "a seat declaring a model without its lineage fails naming all "
                "three seats",
            ],
            list(config_fatal.S11_ASSERTIONS),
        )


class ConfigFatalScenarioBodyTests(unittest.TestCase):
    """What S11 concludes about a product that refuses well, and badly."""

    def test_a_product_that_scaffolds_nothing_still_reports_all_four(self) -> None:
        support.install_fake_runs(self)
        findings = list(DEFAULT_REGISTRY.get("S11").func(None))
        self.assertEqual(list(config_fatal.S11_ASSERTIONS),
                         [finding.assertion for finding in findings])
        self.assertEqual({Outcome.CANNOT_TEST},
                         {finding.outcome for finding in findings})

    def test_a_product_that_refuses_well_passes_every_assertion(self) -> None:
        support.install_fake_runs(self, responder=_FakeProduct())
        self.assertEqual({Outcome.PASS},
                         set(_outcomes().values()))

    def test_one_incompatibility_at_a_time_fails_the_count(self) -> None:
        """The trap the assertion is written around. Reporting the first of
        three is a non-empty message, so a check that only asked whether the
        product complained would pass over exactly this defect.
        """
        support.install_fake_runs(self, responder=_FakeProduct(all_at_once=False))
        outcomes = _outcomes()
        self.assertEqual(Outcome.FAIL,
                         outcomes[config_fatal.S11_ASSERTIONS[2]])

    def test_naming_one_seat_of_three_fails(self) -> None:
        support.install_fake_runs(self, responder=_FakeProduct(seats_named=1))
        outcomes = _outcomes()
        self.assertEqual(Outcome.FAIL,
                         outcomes[config_fatal.S11_ASSERTIONS[3]])

    def test_a_refusal_that_first_contacted_the_backend_fails(self) -> None:
        support.install_fake_runs(self,
                                  responder=_FakeProduct(reaches_backend=True))
        outcomes = _outcomes()
        self.assertEqual(Outcome.FAIL,
                         outcomes[config_fatal.S11_ASSERTIONS[1]])

    def test_the_wrong_exit_code_fails_even_when_the_field_is_named(self) -> None:
        """Refusing and refusing usefully are different guarantees, and the
        operator needs the second one to script against.
        """
        support.install_fake_runs(self, responder=_FakeProduct(exit_code=1))
        outcomes = _outcomes()
        self.assertEqual(Outcome.FAIL,
                         outcomes[config_fatal.S11_ASSERTIONS[0]])

    def test_the_variants_are_written_under_the_scratch_area(self) -> None:
        """REQ-S30: the persistent environment's own configuration is never
        one of the variants, or a broken file would outlive the scenario.
        """
        binary = support.install_fake_runs(self, responder=_FakeProduct())
        list(DEFAULT_REGISTRY.get("S11").func(None))
        scratch = pathlib.Path(str(runs.scratch_root())).resolve()
        for call in binary.calls:
            if call.cwd is None:
                continue
            self.assertTrue(
                pathlib.Path(str(call.cwd)).resolve().is_relative_to(scratch),
                "S11 ran the product outside the scratch area: %s" % call.cwd,
            )


if __name__ == "__main__":
    unittest.main()
