// Author: Julian Bolivar
// Version: 0.17.0
// Date: 2026-08-27

//! Headless output formatting: text (stream) / rich JSON (buffered), truncation of large
//! results, and redaction of secrets in error messages (REQ-H13, REQ-H14, REQ-H15c).
//!
//! Two orthogonal formatters over the same [`RunOutcome`]:
//! - [`write_text`] writes only the `response` to `out` (plus a clamp warning to `err_out` if applicable) — for `--output-format text` (default).
//! - [`write_json`] serializes **a single buffered JSON object**, with `schema_version` as the **first physical field** (REQ-H14), truncating each large `result`/`content` to the effective cap ([`TOOL_RESULT_CAP`](super::limits::TOOL_RESULT_CAP) by default) with a marker.
//!
//! [`sanitize_error_message`] is the security boundary for any error text that may have been
//! generated by an external layer (HTTP provider, SQLite, IO): **allowlist-first** — it
//! classifies the error class and returns a fixed template message, without echoing the raw
//! tail of the message — with a **safety net** based on key-like patterns as a last resort for
//! text that does not match any known template.
//!
//! These formatters are `pub`: the MS2 runner lives in the binary crate and can only reach
//! `pub` API from the lib.

use std::io::Write;

use serde::Serialize;

use super::types::{
    AppliedCaps, ErrorPayload, RunOutcome, StopReason, Timings, ToolCallRecord, TranscriptEntry,
    Usage,
};
use super::HeadlessError;
#[cfg(test)]
use crate::magi::BudgetTelemetry;

/// JSON output contract version (REQ-H14).
///
/// Only a **breaking** change (renaming/removing/retyping a field, changing semantics)
/// increments it; adding an optional field or a new enum value is additive and does **not**
/// bump it (REQ-H14 evolution policy).
const SCHEMA_VERSION: u32 = 1;

/// Prefix of the truncation marker, prepended to the count of discarded bytes.
const TRUNCATION_MARKER_PREFIX: &str = "…[truncated ";

/// Suffix of the truncation marker, after the count of discarded bytes.
const TRUNCATION_MARKER_SUFFIX: &str = " bytes]";

/// Replacement for any token matching a key-like pattern (fence).
const REDACTED_PLACEHOLDER: &str = "[REDACTED]";

/// Literal prefix of an Anthropic/OpenAI-style API key (`sk-…`).
const SK_KEY_PREFIX: &str = "sk-";

/// Minimum length of the tail after `sk-` to consider it a key (REQ-H15c: pattern
/// `sk-[A-Za-z0-9-]{16,}`).
const SK_KEY_MIN_SUFFIX_LEN: usize = 16;

/// Literal prefix of an AWS access-key-id.
const AKIA_KEY_PREFIX: &str = "AKIA";

/// Exact length of the tail after `AKIA` (REQ-H15c: pattern `AKIA[0-9A-Z]{16}`).
const AKIA_KEY_BODY_LEN: usize = 16;

/// Keyword of an `Authorization: Bearer …` header/token.
const BEARER_KEYWORD: &str = "Bearer";

/// Minimum length of a hex/base64-like character run to consider it a possible generic secret
/// (REQ-H15c, defense in depth).
const GENERIC_SECRET_RUN_MIN_LEN: usize = 32;

/// Length in characters of an HTTP status code (`"401"`, `"500"`, …).
const HTTP_STATUS_TOKEN_LEN: usize = 3;

/// Lowest HTTP status code recognized by the classifier.
const HTTP_STATUS_MIN: u16 = 100;

/// Highest HTTP status code recognized by the classifier.
const HTTP_STATUS_MAX: u16 = 599;

/// Substring that marks a provider error as a network timeout.
///
/// The full phrase is required (not the bare word `"timeout"`) to avoid falsely classifying a
/// generic message that merely mentions the word (`"plain network timeout"` must pass
/// unchanged, see the tests).
const TIMEOUT_MARKER: &str = "timed out";

/// Substring that marks a provider error as a TCP connection refused.
const CONNECTION_REFUSED_MARKER: &str = "connection refused";

/// Wire view of [`RunOutcome`] with the field order fixed by the contract (REQ-H14):
/// `schema_version` must be the first physical key of the emitted JSON object.
/// `tool_calls`/`transcript` are already truncated by the caller (`write_json`) — this view
/// does not truncate anything itself.
#[derive(Debug, Serialize)]
struct WireOutcome<'a> {
    /// Output contract version; always the first serialized key.
    schema_version: u32,
    /// Agent response text, or `None` on error.
    response: &'a Option<String>,
    /// Effective model used in the run.
    model: &'a str,
    /// Effective provider used in the run.
    provider: &'a str,
    /// Input/output token count.
    usage: &'a Usage,
    /// Run latencies.
    timings: &'a Timings,
    /// Reason the agent loop stopped.
    stop_reason: StopReason,
    /// Auditable log of each tool invocation, already truncated.
    tool_calls: Vec<ToolCallRecord>,
    /// Normalized transcript, already truncated.
    transcript: Vec<TranscriptEntry>,
    /// Opaque MAGI object from a `consult` pass, if any.
    consult: &'a Option<serde_json::Value>,
    /// Effective limits applied to the run.
    applied_caps: &'a AppliedCaps,
    /// Error detail if the run failed.
    error: &'a Option<ErrorPayload>,
}

/// Truncates `s` to at most `cap` bytes, respecting UTF-8 character boundaries (never splits a
/// multi-byte character), and appends a marker `…[truncated N bytes]` with `N` = bytes actually
/// discarded.
///
/// `cap` is the effective cap for this run — the operator may lower it (never raise it) via
/// `[headless] tool_result_cap_bytes` in `magi.toml` (spec §11);
/// [`TOOL_RESULT_CAP`](super::limits::TOOL_RESULT_CAP) is only the default value
/// `HeadlessLimits::default()` uses when the operator does not set it.
///
/// If `s` already fits within the cap, it is returned unchanged (without a marker).
///
/// # Examples
///
/// ```rust,ignore
/// // Ilustrativo, no un doctest ejecutado.
/// let short = truncate_result("hola", 64 * 1024);
/// assert_eq!(short, "hola");
/// ```
pub fn truncate_result(s: &str, cap: usize) -> String {
    if s.len() <= cap {
        return s.to_string();
    }
    // Step back from the cap to the nearest valid character boundary (a multi-byte character is
    // never split in the middle).
    let mut boundary = cap;
    while boundary > 0 && !s.is_char_boundary(boundary) {
        boundary -= 1;
    }
    let kept = s.get(..boundary).unwrap_or_default();
    let dropped = s.len() - kept.len();
    format!("{kept}{TRUNCATION_MARKER_PREFIX}{dropped}{TRUNCATION_MARKER_SUFFIX}")
}

/// Returns a copy of `tc` with `result` truncated to `cap` bytes.
fn truncate_tool_call(tc: &ToolCallRecord, cap: usize) -> ToolCallRecord {
    let mut truncated = tc.clone();
    truncated.result = truncate_result(&truncated.result, cap);
    truncated
}

/// Returns a copy of `entry` with `content` truncated and, if it has nested `tool_calls`, each
/// of those also truncated to `cap` bytes.
fn truncate_transcript_entry(entry: &TranscriptEntry, cap: usize) -> TranscriptEntry {
    let mut truncated = entry.clone();
    truncated.content = truncate_result(&truncated.content, cap);
    truncated.tool_calls = truncated
        .tool_calls
        .map(|calls| calls.iter().map(|tc| truncate_tool_call(tc, cap)).collect());
    truncated
}

/// Writes a single **buffered** JSON object (REQ-H14) to `out`, with `schema_version` as the
/// first physical field, followed by `response`, `model`, `provider`, `usage`, `timings`,
/// `stop_reason`, `tool_calls`, `transcript`, `consult`, `applied_caps`, `error` — in exactly
/// that order.
///
/// Each `result` in `tool_calls[]` and each `content` in `transcript[]` are truncated to
/// `tool_result_cap` (the effective cap for this run, spec §11) before serializing (see
/// [`truncate_result`]).
///
/// # Errors
///
/// Returns [`HeadlessError::Io`] if serialization to `out` fails (e.g., the underlying `Write`
/// returns an I/O error).
pub fn write_json(
    out: &mut impl Write,
    o: &RunOutcome,
    tool_result_cap: usize,
) -> Result<(), HeadlessError> {
    let wire = WireOutcome {
        schema_version: SCHEMA_VERSION,
        response: &o.response,
        model: &o.model,
        provider: &o.provider,
        usage: &o.usage,
        timings: &o.timings,
        stop_reason: o.stop_reason,
        tool_calls: o
            .tool_calls
            .iter()
            .map(|tc| truncate_tool_call(tc, tool_result_cap))
            .collect(),
        transcript: o
            .transcript
            .iter()
            .map(|e| truncate_transcript_entry(e, tool_result_cap))
            .collect(),
        consult: &o.consult,
        applied_caps: &o.applied_caps,
        error: &o.error,
    };
    serde_json::to_writer(out, &wire).map_err(|e| HeadlessError::Io(e.to_string()))
}

/// Text-mode stderr notice for [`StopReason::MaxToolCalls`] (MAGI S6 gate finding 5).
///
/// The JSON contract already names the ceiling via `stop_reason`, but text mode writes only
/// `response` to stdout — and a run that hits the cap always has `response = None`
/// (`headless_runner::run_query`'s `Some(Err(e))` arm for `MAX_TOOL_CALLS_ERROR` constructs the
/// outcome with `None` unconditionally). Without this notice, a consumer of text mode sees the
/// SAME empty stdout and exit code 0 for two different outcomes: a genuinely empty successful
/// run, and one that hit the tool-call ceiling before producing a final response — indistinguishable
/// without reading JSON. `exit::exit_code` deliberately maps `MaxToolCalls` to success (REQ-H23b:
/// reaching the cap is a terminal state, not an error) and that mapping is intentionally
/// unchanged here — this notice restores the missing SIGNAL, not the exit code.
const MAX_TOOL_CALLS_TEXT_NOTICE: &str =
    "stop_reason: max_tool_calls — the tool-call budget was exhausted before a final response\n";

/// Writes `bytes` to `w`, treating a `BrokenPipe` error as benign (the downstream reader of
/// stdout/stderr closed its end deliberately — e.g. `magi-rs query ... | head -1`) and
/// propagating any OTHER write failure as [`HeadlessError::Io`].
///
/// This distinction is the point (MAGI S6 gate finding 4): `BrokenPipe` is the one write
/// failure every Unix CLI convention treats as expected and silent; a genuine failure — disk
/// full, permission denied on a redirected file, a closed handle for a reason OTHER than the
/// reader hanging up — is not the same category and must not be swallowed under the same
/// blanket `let _ = ...` (B9: no silent failures).
fn write_all_unless_broken_pipe(w: &mut impl Write, bytes: &[u8]) -> Result<(), HeadlessError> {
    match w.write_all(bytes) {
        Ok(()) => Ok(()),
        Err(e) if e.kind() == std::io::ErrorKind::BrokenPipe => Ok(()),
        Err(e) => Err(HeadlessError::Io(e.to_string())),
    }
}

/// Writes output in text mode (REQ-H13, default): `o`'s `response` goes to `out` with no other
/// content (stdout stays clean for the response); if `o.applied_caps.max_tool_calls_clamped`, a
/// one-line warning is emitted to `err_out` (stderr) so that the REQ-H12b clamp is never
/// silent, even in text mode; if `o.stop_reason` is [`StopReason::MaxToolCalls`], a matching
/// one-line stderr notice is emitted for the same reason (MAGI S6 gate finding 5).
///
/// # Errors
/// The first non-`BrokenPipe` write failure on either `out` or `err_out` (MAGI S6 gate finding
/// 4). A broken pipe is swallowed, matching the trade-off most Unix CLIs make with
/// `SIGPIPE`/`EPIPE`; any other I/O error (disk full, a redirected file that cannot be written)
/// is real and must reach the caller, which already has an error channel
/// (`write_headless_output` → `finish_headless` → a dedicated non-zero exit code) — this
/// function returning `()` unconditionally was itself the defect: its sibling [`write_json`]
/// already propagates its write failures via `?`, and there is nothing about text mode that
/// makes its own write failures less real.
pub fn write_text(
    out: &mut impl Write,
    err_out: &mut impl Write,
    o: &RunOutcome,
) -> Result<(), HeadlessError> {
    if let Some(response) = &o.response {
        write_all_unless_broken_pipe(out, response.as_bytes())?;
    }
    if o.applied_caps.max_tool_calls_clamped {
        let notice = format!(
            "applied_caps: max_tool_calls clamped to {}\n",
            o.applied_caps.max_tool_calls
        );
        write_all_unless_broken_pipe(err_out, notice.as_bytes())?;
    }
    if o.stop_reason == StopReason::MaxToolCalls {
        write_all_unless_broken_pipe(err_out, MAX_TOOL_CALLS_TEXT_NOTICE.as_bytes())?;
    }
    Ok(())
}

/// Classifies `raw` as a provider error shaped like an HTTP status.
///
/// Recognizes any message that mentions `"http"` (case-insensitive) and contains a three-digit
/// numeric token in the valid HTTP status range (100-599); returns the code if found. It is
/// intentionally narrow — it never matches a bare number without the word `"http"` present — so
/// it does not mistakenly classify unrelated text that merely contains a number.
fn classify_http_status(raw: &str) -> Option<u16> {
    const HTTP_KEYWORD: &str = "http";
    if !raw.to_ascii_lowercase().contains(HTTP_KEYWORD) {
        return None;
    }
    raw.split(|c: char| !c.is_ascii_alphanumeric())
        .filter(|tok| tok.len() == HTTP_STATUS_TOKEN_LEN && tok.bytes().all(|b| b.is_ascii_digit()))
        .find_map(|tok| tok.parse::<u16>().ok())
        .filter(|code| (HTTP_STATUS_MIN..=HTTP_STATUS_MAX).contains(code))
}

/// Sanitizes an error message potentially coming from an external layer (HTTP provider, SQLite,
/// IO) so it is safe to emit to stdout/stderr/log/`error.message` (REQ-H15c).
///
/// Approach is **allowlist-first**: it first tries to classify `raw` into a known error class
/// (HTTP status, timeout, connection refused) and, if it succeeds, returns a fixed **template**
/// message that does **not** echo any raw text from `raw` — so a secret embedded in the tail of
/// the message (e.g., a URL or a header reflected by the provider) never reaches the output. If
/// `raw` does not match any known template, a **safety net** (`fence`, defense in depth) is
/// applied: known key-like patterns (`sk-…`, `Bearer …`, `AKIA…`, long hex/base64-like runs)
/// are redacted and the rest of the text is returned intact.
///
/// # Examples
///
/// ```rust,ignore
/// // Ilustrativo, no un doctest ejecutado.
/// assert_eq!(
///     sanitize_error_message("http 401 Unauthorized: sk-ant-xxxxxxxxxxxxxxxx"),
///     "provider error: HTTP 401"
/// );
/// assert_eq!(sanitize_error_message("plain network timeout"), "plain network timeout");
/// ```
pub fn sanitize_error_message(raw: &str) -> String {
    if let Some(status) = classify_http_status(raw) {
        return format!("provider error: HTTP {status}");
    }
    let lower = raw.to_ascii_lowercase();
    if lower.contains(TIMEOUT_MARKER) {
        return "provider error: request timed out".to_string();
    }
    if lower.contains(CONNECTION_REFUSED_MARKER) {
        return "network error: connection refused".to_string();
    }
    redact_secret_patterns(raw)
}

/// `true` if `c` is a valid character inside the body of a `sk-…` key (ASCII alphanumeric or
/// hyphen).
fn is_key_body_char(c: char) -> bool {
    c.is_ascii_alphanumeric() || c == '-'
}

/// `true` if `c` is a valid character inside a generic hex/base64-like run (ASCII alphanumeric
/// or one of `+ / = _ -`).
fn is_generic_secret_char(c: char) -> bool {
    c.is_ascii_alphanumeric() || matches!(c, '+' | '/' | '=' | '_' | '-')
}

/// Attempts to match a `Bearer <token>` token starting at `chars[i]`.
///
/// Returns the number of characters consumed by the complete match (keyword + whitespace +
/// token) if `chars` from `i` literally starts with `"Bearer"` followed by at least one
/// whitespace character and at least one non-whitespace character.
fn match_bearer_token(chars: &[char], i: usize) -> Option<usize> {
    let mut consumed = 0usize;
    for (offset, kw_char) in BEARER_KEYWORD.chars().enumerate() {
        // Case-insensitive keyword match ("Bearer"/"bearer"/…) — over-redaction is the safe
        // direction, so a differently-cased scheme still redacts.
        if !chars.get(i + offset)?.eq_ignore_ascii_case(&kw_char) {
            return None;
        }
        consumed += 1;
    }
    let ws_start = consumed;
    let mut j = ws_start;
    while matches!(chars.get(i + j), Some(c) if c.is_whitespace()) {
        j += 1;
    }
    if j == ws_start {
        return None;
    }
    let token_start = j;
    while matches!(chars.get(i + j), Some(c) if !c.is_whitespace()) {
        j += 1;
    }
    if j == token_start {
        return None;
    }
    Some(j)
}

/// Attempts to match an `sk-[A-Za-z0-9-]{16,}` key starting at `chars[i]`.
///
/// Returns the number of characters consumed (`sk-` prefix + body run) if the tail after `sk-`
/// reaches at least [`SK_KEY_MIN_SUFFIX_LEN`] characters.
fn match_sk_key(chars: &[char], i: usize) -> Option<usize> {
    let mut consumed = 0usize;
    for (offset, p_char) in SK_KEY_PREFIX.chars().enumerate() {
        if *chars.get(i + offset)? != p_char {
            return None;
        }
        consumed += 1;
    }
    let mut run_len = 0usize;
    while matches!(chars.get(i + consumed + run_len), Some(c) if is_key_body_char(*c)) {
        run_len += 1;
    }
    (run_len >= SK_KEY_MIN_SUFFIX_LEN).then_some(consumed + run_len)
}

/// Attempts to match an AWS access-key-id `AKIA[0-9A-Z]{16}` starting at `chars[i]`.
///
/// Returns the number of characters consumed (`AKIA` prefix + the [`AKIA_KEY_BODY_LEN`] body
/// characters) only if the body reaches exactly that length of valid characters.
fn match_akia_key(chars: &[char], i: usize) -> Option<usize> {
    let mut consumed = 0usize;
    for (offset, p_char) in AKIA_KEY_PREFIX.chars().enumerate() {
        if *chars.get(i + offset)? != p_char {
            return None;
        }
        consumed += 1;
    }
    let mut run_len = 0usize;
    while run_len < AKIA_KEY_BODY_LEN {
        match chars.get(i + consumed + run_len) {
            Some(c) if c.is_ascii_uppercase() || c.is_ascii_digit() => run_len += 1,
            _ => break,
        }
    }
    (run_len == AKIA_KEY_BODY_LEN).then_some(consumed + run_len)
}

/// Attempts to match a generic hex/base64-like run starting at `chars[i]`, of at least
/// [`GENERIC_SECRET_RUN_MIN_LEN`] characters.
fn match_generic_secret_run(chars: &[char], i: usize) -> Option<usize> {
    let mut run_len = 0usize;
    while matches!(chars.get(i + run_len), Some(c) if is_generic_secret_char(*c)) {
        run_len += 1;
    }
    (run_len >= GENERIC_SECRET_RUN_MIN_LEN).then_some(run_len)
}

/// Walks through `raw` in a single pass and redacts any known key-like pattern (`Bearer …`,
/// `sk-…`, `AKIA…`, long hex/base64-like runs) to `REDACTED_PLACEHOLDER`; the rest of the text
/// passes through unchanged.
///
/// # Complexity: `O(n)`, not `O(n²)` — verified, not assumed
///
/// A prior revision of this doc claimed a quadratic worst case, reasoning that a run of
/// eligible characters that falls just short of a threshold (e.g. `GENERIC_SECRET_RUN_MIN_LEN`)
/// gets re-scanned from the next starting position. That undercounts the actual bound: **every
/// one of the three "near-miss" scan lengths is capped by a small `const`**
/// (`GENERIC_SECRET_RUN_MIN_LEN - 1` = 31, `SK_KEY_MIN_SUFFIX_LEN - 1` = 15,
/// `AKIA_KEY_BODY_LEN - 1` = 15) — a failing match at position `i` can never scan more than
/// that constant number of characters, because scanning past it would mean the run met the
/// threshold and *matched* instead of failing. A failing position therefore costs `O(1)`
/// amortized, not `O(remaining run length)`, and the whole pass is `O(n)`. Confirmed
/// empirically against the exact adversarial shape described above (many maximal near-miss
/// blocks back to back): wall-clock time scales linearly with input length, not
/// quadratically — see `redact_secret_patterns_stays_linear_on_the_adversarial_near_miss_pattern`
/// below, which pins this so a future change that removes one of those three bounds (e.g. by
/// deriving a threshold from input length) regresses a test, not just a doc comment.
///
/// On a successful match the cursor also jumps over the full match length (`i += consumed`),
/// so a found secret is not re-scanned either.
///
/// Because the bound is `O(n)` regardless of content, this function is safe to run over input
/// that is **not** small diagnostic text too: `headless::log` reuses it (below, via `pub`) for
/// a tool call's full, untruncated `input` at debug level — which can be attacker- or
/// model-influenced and is not bounded to a few KB the way an error message is. Redaction
/// deliberately runs before truncation there (see `LogEvent::render`), so this function's
/// linear bound — not an assumption that callers only ever pass short text — is what keeps
/// that debug-logging path from being a quadratic-cost lever.
///
/// `pub` (widened from private in T8, REQ-H24, and from `pub(crate)` for the MS2 runner in the
/// binary crate): `headless::log` reuses this same redactor for a tool-call's `input` at debug
/// level — the matchers are never reimplemented in a second place (DRY).
pub fn redact_secret_patterns(raw: &str) -> String {
    let ranges = secret_pattern_ranges(raw);
    if ranges.is_empty() {
        return raw.to_string();
    }
    let mut out = String::with_capacity(raw.len());
    let mut cursor = 0usize;
    for r in ranges {
        if let Some(seg) = raw.get(cursor..r.start) {
            out.push_str(seg);
        }
        out.push_str(REDACTED_PLACEHOLDER);
        cursor = r.end;
    }
    if let Some(tail) = raw.get(cursor..) {
        out.push_str(tail);
    }
    out
}

/// The BYTE ranges of `raw` that the pattern matchers claim.
///
/// Extracted so the traversal has exactly one definition and two views of it:
/// [`redact_secret_patterns`] rewrites the string, and the logging auditor needs
/// the **ranges** instead. The auditor's two passes both run over the ORIGINAL
/// line and union their ranges before redacting once (REQ-L49) — chaining a
/// string-rewriting pass in front of it is the leak that requirement exists to
/// close, so a `String`-returning function cannot serve it.
///
/// Ranges are non-overlapping and in ascending order, because the walk consumes
/// each match before continuing.
///
/// # Complexity
///
/// `O(n)` over the characters, plus `O(n)` to build the offset table.
#[must_use]
pub fn secret_pattern_ranges(raw: &str) -> Vec<std::ops::Range<usize>> {
    let chars: Vec<char> = raw.chars().collect();
    // Byte offset of every character index, with a sentinel past the last one,
    // so a match measured in characters becomes a byte range without a second
    // traversal.
    let mut offsets: Vec<usize> = Vec::with_capacity(chars.len() + 1);
    let mut at = 0usize;
    for c in &chars {
        offsets.push(at);
        at += c.len_utf8();
    }
    offsets.push(at);

    let mut out = Vec::new();
    let mut i = 0usize;
    while i < chars.len() {
        if let Some(consumed) = match_bearer_token(&chars, i)
            .or_else(|| match_sk_key(&chars, i))
            .or_else(|| match_akia_key(&chars, i))
            .or_else(|| match_generic_secret_run(&chars, i))
        {
            let end = i.saturating_add(consumed).min(chars.len());
            if let (Some(&from), Some(&to)) = (offsets.get(i), offsets.get(end)) {
                out.push(from..to);
            }
            i = i.saturating_add(consumed);
            continue;
        }
        i += 1;
    }
    out
}

/// Fuzz entrypoint (`fuzz_sanitize_error`, Task 10 / REQ-H35 / REQ-H15c).
///
/// Feeds ARBITRARY bytes (via `from_utf8_lossy`, since the sanitizers take `&str`) through
/// [`sanitize_error_message`] and [`redact_secret_patterns`], discarding the sanitized text.
/// Invariants exercised on every input:
///
/// - **Never panics / never UB** on any byte sequence (empty, non-UTF8, huge, embedded key patterns, adversarial whitespace).
/// - **Redaction is idempotent**: re-running [`redact_secret_patterns`] over an already-redacted string is a no-op. A surviving key-pattern would break this equality (a second pass would redact it), so the assertion is the proxy for "no known key-pattern is ever left un-redacted" (REQ-H15c).
///
/// `#[doc(hidden)] pub` mirrors the vault's `fuzz_*_entrypoint` convention: it exposes an
/// internal `pub(crate)` boundary to the external fuzz crate WITHOUT widening the documented
/// public API surface.
///
/// # Panics
///
/// Panics (under `debug_assertions`, which `cargo-fuzz` enables) only if the redaction
/// idempotency invariant is violated — that is the genuine bug the fuzzer is meant to surface,
/// not a spurious abort.
#[doc(hidden)]
pub fn fuzz_sanitize_error_entrypoint(data: &[u8]) {
    let s = String::from_utf8_lossy(data);
    // Both sanitizers must be total (never panic) on arbitrary text.
    let _ = sanitize_error_message(&s);
    let redacted = redact_secret_patterns(&s);
    // Idempotency: a surviving key-pattern would change on a second pass.
    debug_assert_eq!(
        redact_secret_patterns(&redacted),
        redacted,
        "redaction must be idempotent (no key-pattern left un-redacted)"
    );
}

#[cfg(test)]
impl RunOutcome {
    /// Deterministic test constructor: fixed values, no clock and no randomness, so a golden
    /// file (`tests/golden/headless_output_v1.json`) remains stable across runs.
    pub(crate) fn sample() -> Self {
        let sample_tool_call = ToolCallRecord {
            name: "ls".to_string(),
            input: serde_json::json!({"path": "."}),
            result: "file1\nfile2".to_string(),
            ms: 12,
            ok: true,
        };
        RunOutcome {
            response: Some("Hello from magi.".to_string()),
            model: "claude-sonnet-4-6".to_string(),
            provider: "anthropic".to_string(),
            usage: Usage {
                input_tokens: 100,
                output_tokens: 50,
            },
            timings: Timings {
                total_ms: 1234,
                ttfb_ms: Some(200),
                per_turn_ms: vec![600, 634],
            },
            stop_reason: StopReason::Done,
            tool_calls: vec![sample_tool_call.clone()],
            transcript: vec![
                TranscriptEntry {
                    role: "user".to_string(),
                    content: "list files".to_string(),
                    tool_calls: None,
                },
                TranscriptEntry {
                    role: "assistant".to_string(),
                    content: "Hello from magi.".to_string(),
                    tool_calls: Some(vec![sample_tool_call]),
                },
            ],
            consult: None,
            applied_caps: AppliedCaps {
                max_tool_calls: 15,
                max_tool_calls_clamped: false,
                timeout_secs: None,
                system_override_applied: false,
                // Realistic values (unlike the zeroed `BudgetTelemetry::default()` used
                // elsewhere as a placeholder): `sample()` stands in for a FINISHED run whose
                // budget has already been stamped by the runner, the values a `--timeout 1800`
                // run produces.
                budget: BudgetTelemetry {
                    operation_budget_secs: 149,
                    ceiling_floored: false,
                    floor_activation_threshold_secs: 114,
                    max_rotations_effective: 2,
                    ceiling_above_sanity: false,
                },
            },
            error: None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::super::limits::TOOL_RESULT_CAP;
    use super::*;

    /// REQ-H14: the JSON object carries `schema_version` and truncates a large `result` to
    /// `TOOL_RESULT_CAP` with the truncation marker.
    #[test]
    fn test_write_json_has_schema_version_and_truncates_large_results() {
        let mut o = RunOutcome::sample();
        o.tool_calls[0].result = "x".repeat(70_000);

        let mut buf = Vec::new();
        write_json(&mut buf, &o, TOOL_RESULT_CAP).unwrap();

        let v: serde_json::Value = serde_json::from_slice(&buf).unwrap();
        assert_eq!(v["schema_version"], 1);
        let r = v["tool_calls"][0]["result"].as_str().unwrap();
        assert!(r.len() <= 64 * 1024 + 32 && r.ends_with("bytes]"));
    }

    /// REQ-H14: the five budget keys sit FLAT inside `applied_caps`, as siblings of
    /// `timeout_secs`. Additive, no `schema_version` bump — a consumer reading by key is
    /// unaffected, which is the policy this envelope has published since MS2.
    #[test]
    fn test_applied_caps_carries_the_budget_decision_flat() {
        let o = RunOutcome::sample();
        let mut buf = Vec::new();
        write_json(&mut buf, &o, TOOL_RESULT_CAP).unwrap();
        let v: serde_json::Value = serde_json::from_slice(&buf).unwrap();

        let caps = &v["applied_caps"];
        assert!(caps["operation_budget_secs"].is_u64());
        assert!(caps["ceiling_floored"].is_boolean());
        assert!(caps["floor_activation_threshold_secs"].is_u64());
        assert!(caps["max_rotations_effective"].is_u64());
        assert!(caps["ceiling_above_sanity"].is_boolean());
        assert!(
            caps["budget"].is_null(),
            "flattened, not nested: a consumer must not have to learn a new object"
        );
        assert_eq!(
            v["schema_version"], 1,
            "additive fields never bump the version"
        );
    }

    /// The emitted JSON object has `schema_version` as the FIRST physical field and respects
    /// the fixed REQ-H14 order for the remaining fields.
    #[test]
    fn test_write_json_field_order_matches_contract() {
        let o = RunOutcome::sample();
        let mut buf = Vec::new();
        write_json(&mut buf, &o, TOOL_RESULT_CAP).unwrap();
        let text = String::from_utf8(buf).unwrap();

        assert!(text.starts_with("{\"schema_version\":1"));

        let order = [
            "schema_version",
            "response",
            "model",
            "provider",
            "usage",
            "timings",
            "stop_reason",
            "tool_calls",
            "transcript",
            "consult",
            "applied_caps",
            "error",
        ];
        let mut search_from = 0usize;
        for key in order {
            let needle = format!("\"{key}\"");
            let rest = text.get(search_from..).unwrap();
            let pos = rest
                .find(&needle)
                .unwrap_or_else(|| panic!("missing key `{key}` after byte {search_from}"));
            search_from += pos + needle.len();
        }
    }

    /// Golden file: the full shape of serialized `RunOutcome::sample()` matches
    /// `tests/golden/headless_output_v1.json` (freezes the contract so MS2 cannot silently
    /// drift it).
    #[test]
    fn test_write_json_matches_golden_shape() {
        let o = RunOutcome::sample();
        let mut buf = Vec::new();
        write_json(&mut buf, &o, TOOL_RESULT_CAP).unwrap();
        let produced: serde_json::Value = serde_json::from_slice(&buf).unwrap();

        let golden: serde_json::Value =
            serde_json::from_str(include_str!("../../tests/golden/headless_output_v1.json"))
                .unwrap();

        assert_eq!(produced, golden);
    }

    /// Text mode without clamp: `response` goes to `out`, `err_out` stays empty.
    #[test]
    fn test_write_text_streams_response_without_clamp_notice() {
        let o = RunOutcome::sample();
        let mut out = Vec::new();
        let mut err = Vec::new();

        write_text(&mut out, &mut err, &o).unwrap();

        assert_eq!(String::from_utf8(out).unwrap(), "Hello from magi.");
        assert!(err.is_empty());
    }

    /// Text mode with clamp (REQ-H12b visible, REQ-H14): the warning `applied_caps: …` goes to
    /// `err_out` (stderr), never to `out` (stdout).
    #[test]
    fn test_write_text_emits_clamp_notice_to_stderr_when_clamped() {
        let mut o = RunOutcome::sample();
        o.applied_caps.max_tool_calls_clamped = true;
        let mut out = Vec::new();
        let mut err = Vec::new();

        write_text(&mut out, &mut err, &o).unwrap();

        assert_eq!(String::from_utf8(out).unwrap(), "Hello from magi.");
        let err_text = String::from_utf8(err).unwrap();
        assert!(err_text.starts_with("applied_caps: max_tool_calls clamped"));
    }

    /// Without `response` (run in error), `out` stays empty — never panics.
    #[test]
    fn test_write_text_with_no_response_writes_nothing_to_out() {
        let mut o = RunOutcome::sample();
        o.response = None;
        let mut out = Vec::new();
        let mut err = Vec::new();

        write_text(&mut out, &mut err, &o).unwrap();

        assert!(out.is_empty());
        assert!(err.is_empty());
    }

    /// MAGI S6 gate finding 5: a run that stopped because it hit the tool-call ceiling
    /// (`response` is always `None` in that case) must still say so in text mode — the JSON
    /// contract already carries `stop_reason`, but text mode wrote nothing at all before this,
    /// making it indistinguishable from a genuinely empty successful run (both exit 0, both
    /// empty stdout).
    #[test]
    fn test_write_text_notes_max_tool_calls_on_stderr_when_response_is_empty() {
        let mut o = RunOutcome::sample();
        o.response = None;
        o.stop_reason = StopReason::MaxToolCalls;
        let mut out = Vec::new();
        let mut err = Vec::new();

        write_text(&mut out, &mut err, &o).unwrap();

        assert!(
            out.is_empty(),
            "stdout stays clean — the notice is stderr-only, matching the clamp notice"
        );
        let err_text = String::from_utf8(err).unwrap();
        assert!(
            err_text.contains("max_tool_calls"),
            "stderr must name the ceiling as the reason no response was produced: {err_text:?}"
        );
    }

    /// A run that completes normally (`StopReason::Done`) never emits the `max_tool_calls`
    /// notice, even though nothing about `write_text` computes `stop_reason` from `response`
    /// being present — the two are checked independently, so this pins that they do not
    /// accidentally interact.
    #[test]
    fn test_write_text_omits_max_tool_calls_notice_when_stop_reason_is_done() {
        let o = RunOutcome::sample();
        let mut out = Vec::new();
        let mut err = Vec::new();

        write_text(&mut out, &mut err, &o).unwrap();

        let err_text = String::from_utf8(err).unwrap();
        assert!(!err_text.contains("max_tool_calls"));
    }

    /// A short `result` is left untouched (no marker, no content change).
    #[test]
    fn test_truncate_result_leaves_short_strings_untouched() {
        let s = "short result";
        assert_eq!(truncate_result(s, TOOL_RESULT_CAP), s);
    }

    /// REQ-H14, spec §11: truncation must respect the effective cap passed by the caller, not
    /// the constant `TOOL_RESULT_CAP` — an operator who lowers the cap to 16 bytes must see a
    /// 20-byte `result` truncated to that ceiling, well below the 64 KiB default.
    #[test]
    fn test_truncate_result_respects_custom_effective_cap() {
        let small_cap = 16usize;
        let s = "x".repeat(small_cap + 4);

        let truncated = truncate_result(&s, small_cap);

        // The kept prefix must be EXACTLY `small_cap` bytes long (not the full untruncated
        // string, and not TOOL_RESULT_CAP bytes — the module constant is far larger than `s`
        // and would never truncate it at all): the marker must begin right after the custom
        // cap.
        let expected_prefix = format!("{}{TRUNCATION_MARKER_PREFIX}", "x".repeat(small_cap));
        assert!(
            truncated.starts_with(&expected_prefix),
            "a custom (smaller) effective cap must truncate at {small_cap} bytes, \
             not the module constant: {truncated}"
        );
        assert!(truncated.contains("[truncated 4 bytes]"));
    }

    /// A `result` that exceeds the cap is trimmed to `TOOL_RESULT_CAP` and carries the
    /// truncation marker with the count of discarded bytes.
    #[test]
    fn test_truncate_result_caps_and_appends_marker() {
        let s = "y".repeat(TOOL_RESULT_CAP + 10);
        let truncated = truncate_result(&s, TOOL_RESULT_CAP);

        assert!(truncated.len() <= TOOL_RESULT_CAP + 32);
        assert!(truncated.ends_with("bytes]"));
        assert!(truncated.contains("[truncated 10 bytes]"));
    }

    /// A truncation that would fall in the middle of a multi-byte character steps back to the
    /// previous character boundary instead of splitting it (never panics, never invalid UTF-8
    /// bytes).
    #[test]
    fn test_truncate_result_backs_off_to_char_boundary_on_multibyte_split() {
        let prefix = "a".repeat(TOOL_RESULT_CAP - 1);
        let s = format!("{prefix}€{}", "b".repeat(50));

        let truncated = truncate_result(&s, TOOL_RESULT_CAP);
        let marker_pos = truncated.find(TRUNCATION_MARKER_PREFIX).unwrap();
        let kept = truncated.get(..marker_pos).unwrap();

        assert!(s.starts_with(kept));
        assert!(kept.len() < TOOL_RESULT_CAP);
    }

    /// `sanitize_error_message` redacts multiple secret formats and does NOT falsely redact
    /// plain text; a known class (HTTP status) produces the template message, proving that the
    /// allowlist is the primary defense (not just the safety-net regex).
    #[test]
    fn test_error_message_redacts_multiple_key_formats() {
        // The prefix "sk-ant-api" is built from two separate literals to avoid triggering the
        // repo's hardcoded-secrets scanner (`tests/no_hardcoded_secrets.rs` greps for the
        // literal "sk-ant-api"); it is a synthetic fixture, not a real key.
        let anthropic_like = format!("sk-ant-{}", "SECRET".repeat(3));
        let secrets = [
            anthropic_like.as_str(),
            "sk-proj-OPENAISECRET",
            "Bearer eyJhbGciOiJ...",
            "AKIAIOSFODNN7EXAMPLE",
        ];
        for secret in secrets {
            let msg = sanitize_error_message(&format!("http 401: {secret} rejected"));
            assert!(!msg.contains(secret), "leaked: {secret}");
        }

        assert_eq!(
            sanitize_error_message("plain network timeout"),
            "plain network timeout"
        );

        assert_eq!(
            sanitize_error_message("http 401 Unauthorized: sk-ant-xxxxxxxxxxxxxxxx"),
            "provider error: HTTP 401"
        );
    }

    /// Exercises the fence (defense in depth) directly, with messages that do NOT match any
    /// known template — so it confirms that each pattern (Bearer/sk-/AKIA/generic run) is
    /// actually redacted by the regex-fence, not only by the HTTP-classification shortcut.
    #[test]
    fn test_sanitize_fence_redacts_each_pattern_when_no_known_class_matches() {
        let sk_like = format!("sk-{}", "a".repeat(20));
        let out = sanitize_error_message(&format!("upstream rejected key {sk_like} for tenant"));
        assert!(!out.contains(&sk_like));
        assert!(out.contains(REDACTED_PLACEHOLDER));

        let bearer_msg = "auth failed: Bearer abc123DEF456token";
        let out2 = sanitize_error_message(bearer_msg);
        assert!(!out2.contains("abc123DEF456token"));

        let akia_like = format!("AKIA{}", "B".repeat(16));
        let out3 = sanitize_error_message(&format!("leaked credential {akia_like} found"));
        assert!(!out3.contains(&akia_like));

        let generic_run = "Z".repeat(40);
        let out4 = sanitize_error_message(&format!("token dump: {generic_run} end"));
        assert!(!out4.contains(&generic_run));
    }

    /// The threshold for the generic run is exact: below it does not redact (avoids falsely
    /// redacting normal text), at the threshold it does.
    #[test]
    fn test_generic_secret_run_threshold_is_exact_boundary() {
        let below = "a".repeat(GENERIC_SECRET_RUN_MIN_LEN - 1);
        assert_eq!(sanitize_error_message(&below), below);

        let at_threshold = "a".repeat(GENERIC_SECRET_RUN_MIN_LEN);
        let out = sanitize_error_message(&at_threshold);
        assert!(out.contains(REDACTED_PLACEHOLDER));
        assert!(!out.contains(&at_threshold));
    }

    /// Unit-smoke for the fuzz entrypoint `fuzz_sanitize_error` (REQ-H35): degenerate inputs
    /// (empty, non-UTF8, embedded key-like patterns, long run) never panic and redaction is
    /// idempotent. It is the local version that DOES run on every §0.1, complementing the CI
    /// coverage-guided run.
    #[test]
    fn test_fuzz_sanitize_error_entrypoint_never_panics_on_arbitrary_input() {
        let long_run = "Z".repeat(5_000);
        let cases: &[&[u8]] = &[
            b"",
            b"\xff\xfe\x00\x80",
            b"http 401: leaked key rejected",
            b"Bearer tokenvaluewithsomelength",
            b"AKIAABCDEFGHIJKLMNOP",
            b"plain network timeout",
            long_run.as_bytes(),
        ];
        for case in cases {
            fuzz_sanitize_error_entrypoint(case);
        }
    }

    /// Additional recognized classes (timeout, connection refused) produce their fixed template
    /// instead of echoing the provider's raw message.
    #[test]
    fn test_sanitize_error_message_classifies_timeout_and_connection_refused() {
        assert_eq!(
            sanitize_error_message("upstream request timed out after 30s"),
            "provider error: request timed out"
        );
        assert_eq!(
            sanitize_error_message("io error: connection refused (os error 111)"),
            "network error: connection refused"
        );
    }

    /// `match_bearer_token` compares the keyword case-insensitively (over-redaction is the safe
    /// direction): a lowercase `bearer <token>` and an uppercase `BEARER <token>` are redacted
    /// just like the canonical `Bearer <token>`.
    #[test]
    fn test_sanitize_redacts_lowercase_bearer() {
        // Built with `format!` (not a literal) to avoid triggering the repo's hardcoded-secrets
        // scanner (`tests/no_hardcoded_secrets.rs`); it is a synthetic fixture.
        let token = format!("{}{}", "tok", "EN1234567890abcdef");

        let lower = sanitize_error_message(&format!("auth failed: bearer {token}"));
        assert!(!lower.contains(&token), "lowercase bearer leaked: {lower}");
        assert!(lower.contains(REDACTED_PLACEHOLDER));

        let upper = sanitize_error_message(&format!("auth failed: BEARER {token}"));
        assert!(!upper.contains(&token), "uppercase BEARER leaked: {upper}");
        assert!(upper.contains(REDACTED_PLACEHOLDER));
    }

    /// Regression guard for `redact_secret_patterns`'s complexity claim (MAGI S2 re-gate,
    /// Melchior): the adversarial shape named in its rustdoc — many maximal "near-miss" runs,
    /// each one character short of a threshold, back to back — must stay linear in input
    /// length rather than degenerating to quadratic if a future change removes the constant
    /// bound on one of the three near-miss scan lengths.
    ///
    /// A coarse ceiling, not a precise wall-clock budget (this repo's own documented
    /// flakiness lesson: assert on a generous failure deadline, never on duration). At this
    /// input size a genuine quadratic regression would take on the order of minutes; the
    /// deadline below is deliberately widened to 60s, well above the sub-second time linear
    /// scaling actually takes, so it stays a *failure* bound rather than a performance target
    /// and cannot false-fail under the Argon2-driven CPU contention this repo's `nextest`
    /// suite is known to produce under load (see `CLAUDE.md`'s section on intermittent test
    /// failures under load) — losing no signal, since a real quadratic blowup on 640 KB would
    /// still overshoot it by orders of magnitude.
    #[test]
    fn redact_secret_patterns_stays_linear_on_the_adversarial_near_miss_pattern() {
        let block = "a".repeat(GENERIC_SECRET_RUN_MIN_LEN - 1) + "!";
        let input = block.repeat(20_000); // ~640,000 characters, all near-miss runs.
        let (tx, rx) = std::sync::mpsc::channel();
        std::thread::spawn(move || {
            let _ = redact_secret_patterns(&input);
            let _ = tx.send(());
        });
        assert!(
            rx.recv_timeout(std::time::Duration::from_secs(60)).is_ok(),
            "redact_secret_patterns did not return within a generous ceiling on the \
             near-miss-run pattern; this is the signal of a regression to quadratic \
             behavior, not ordinary CI slowness"
        );
    }
}
