// Author: Julian Bolivar
// Version: 0.17.0
// Date: 2026-08-27
// contract (MS1 ↔ MS2).
//!
//! DEFINED here, not referenced without definition — avoids the TDD-ordering build break (T6
//! uses `AppliedCaps` before T7 exists). The types are declared `pub` with their fields +
//! derives: T6 consumes [`AppliedCaps`]/[`SystemPolicy`]; T7 implements the formatting and
//! golden over [`RunOutcome`] and company. MS2
//! **fills** these types with the actual `Agent` output from the crate of the
//! binary, which can only reach the lib's `pub` API (not `pub(crate)`).
//!
//! The actual consumers of these types arrive in later tasks of the same milestone (T6/T7) and
//! in the binary runner (MS2).

use serde::Serialize;

/// Complete result of a headless run (`magi query`/`consult`).
///
/// It is the **stable** projection that the contract serializes (REQ-H14), decoupled from the
/// `Agent`'s internal `Message`: MS2 fills it, not redefines it.
#[derive(Debug, Clone, Serialize)]
pub struct RunOutcome {
    /// Agent response text; `None` if the run ended in error.
    pub response: Option<String>,
    /// Effective model used in the run.
    pub model: String,
    /// Effective provider used in the run.
    pub provider: String,
    /// Input/output token count (billing/observability).
    pub usage: Usage,
    /// Run latencies (total and, optionally, per turn).
    pub timings: Timings,
    /// Reason why the agent loop stopped.
    pub stop_reason: StopReason,
    /// Auditable record of each tool invocation.
    pub tool_calls: Vec<ToolCallRecord>,
    /// Normalized transcription by message (stable projection).
    pub transcript: Vec<TranscriptEntry>,
    /// Opaque MAGI object from a `consult` pass; `None` if there was none.
    pub consult: Option<serde_json::Value>,
    /// Effective limits after applying operator caps and envelope clamps.
    pub applied_caps: AppliedCaps,
    /// Error detail if the run failed; `None` on success.
    pub error: Option<ErrorPayload>,
}

/// Token count consumed by the run.
#[derive(Debug, Clone, Serialize)]
pub struct Usage {
    /// Input tokens (prompt + context + tool results).
    pub input_tokens: u64,
    /// Output tokens generated by the model.
    pub output_tokens: u64,
}

/// Latencies observed during the run.
#[derive(Debug, Clone, Serialize)]
pub struct Timings {
    /// Total duration of the run in milliseconds.
    pub total_ms: u64,
    /// Time-to-first-byte of the first token, if measured.
    pub ttfb_ms: Option<u64>,
    /// Duration of each loop turn, in order.
    pub per_turn_ms: Vec<u64>,
}

/// Reason why the agent loop stopped.
///
/// Priority when they co-occur (REQ-H14): `Error` > `MaxToolCalls` > `Denied` > `Done`.
/// Serializes as `snake_case` (stable contract).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum StopReason {
    /// The agent completed and produced its final response.
    Done,
    /// The tool invocation cap was reached.
    MaxToolCalls,
    /// An essential tool was denied by the tier and blocked the task.
    Denied,
    /// The run ended in error (includes timeout and repetitive guard).
    Error,
}

/// Auditable record of a single tool invocation.
#[derive(Debug, Clone, Serialize)]
pub struct ToolCallRecord {
    /// Name of the invoked tool.
    pub name: String,
    /// JSON input with which the tool was invoked.
    pub input: serde_json::Value,
    /// Tool result (truncated to `TOOL_RESULT_CAP` by the formatter).
    pub result: String,
    /// Duration of the invocation in milliseconds.
    pub ms: u64,
    /// `true` if the tool ran successfully; `false` if it failed or was denied.
    pub ok: bool,
}

/// One entry in the normalized transcript (one per message).
#[derive(Debug, Clone, Serialize)]
pub struct TranscriptEntry {
    /// Normalized message role (`assistant`/`user`/`tool`).
    pub role: String,
    /// Textual content of the message.
    pub content: String,
    /// Tool invocations associated with the message, if any.
    pub tool_calls: Option<Vec<ToolCallRecord>>,
}

/// Effective limits applied to the run (makes the REQ-H12b clamp visible).
///
/// This struct's own serialized field count is mirrored by hand in `APPLIED_CAPS_OWN_FIELDS`
/// in this module's tests. Adding or removing a field here means updating that constant too;
/// the flatten collision guard test will fail loudly if you forget.
#[derive(Debug, Clone, Serialize)]
pub struct AppliedCaps {
    /// Effective tool invocation cap after applying the operator cap.
    pub max_tool_calls: u32,
    /// `true` if the envelope's `max_tool_calls` was cut to the cap.
    pub max_tool_calls_clamped: bool,
    /// Wall-clock cap in seconds, if one was set.
    pub timeout_secs: Option<u64>,
    /// `true` if the envelope's `system` was applied (requires the operator flag).
    pub system_override_applied: bool,
    /// How this run's per-mage budget was decided (REQ-EB02b/EB04).
    ///
    /// **Flattened**: its five fields serialize as siblings of the ones above, not as a nested
    /// object, so a consumer reads `applied_caps.operation_budget_secs` and never learns a new
    /// shape. Additive under REQ-H14 — no `schema_version` bump.
    ///
    /// One field rather than five because the values travel together from `main.rs` through
    /// `RunWiring`, exactly as `timeout_secs` does: five loose fields would be five things to
    /// thread twice and five chances to drop one.
    ///
    /// # INVARIANT: the two field-name sets must stay DISJOINT
    ///
    /// Flattening makes `BudgetTelemetry`'s names siblings of this struct's own. If a field added
    /// to **either** struct ever collides by name, `serde_json` writes the key twice into one
    /// map — the second write wins and the first value **vanishes from the output with no error,
    /// no warning, and a still-valid JSON document**. Nothing in the type system prevents it: the
    /// two structs are in different files and neither mentions the other's names.
    ///
    /// Before adding a field to `AppliedCaps` or to `BudgetTelemetry`, check the other one.
    /// `the_flattened_budget_keeps_every_key_of_both_structs` is what fails if you forget.
    ///
    /// **`Deserialize` note (Step 5b):** `AppliedCaps` derives `Serialize` only — this crate
    /// writes the envelope and never reads it back, so flatten's known interaction problems with
    /// `deny_unknown_fields` and non-self-describing formats do not apply today. If `Deserialize`
    /// is ever added to this struct, `BudgetTelemetry` would need it too, and those limitations
    /// come back into scope — revisit this field at that point.
    #[serde(flatten)]
    pub budget: crate::magi::BudgetTelemetry,
}

/// Structured detail of a run error in the JSON output.
#[derive(Debug, Clone, Serialize)]
pub struct ErrorPayload {
    /// Safe message (already sanitized; never a raw secret).
    pub message: String,
    /// Error class, so the caller can route without parsing the message.
    pub kind: ErrorKind,
}

/// Error class of a headless run (maps 1:1 to an exit code, REQ-H14).
///
/// Serializes as `snake_case`. A new enum value is **additive** (REQ-H14): the consumer must
/// treat an unknown value as catch-all, not break.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ErrorKind {
    /// Invalid input / bad CLI usage (→ exit 2).
    InputInvalid,
    /// Corrupt DB: data present without envelope (→ exit 1, never-delete).
    DbCorrupt,
    /// Incorrect passphrase; retryable, never deletes (→ exit 1 in headless).
    WrongPassphrase,
    /// No passphrase and no TTY to ask for it (→ exit 1).
    PassphraseUnavailable,
    /// An essential tool was denied by the tier and blocked the task (→ exit 3).
    TierDenied,
    /// LLM provider failure (HTTP/network), with sanitized message (→ exit 1).
    Provider,
    /// The wall-clock `--timeout` expired (→ exit 1). First-class class.
    Timeout,
    /// Any other agent runtime error (→ exit 1).
    Runtime,
}

/// Effective system prompt of the run together with its **origin** (REQ-H12b).
///
/// The origin is a safety limit: the envelope's `system` is only honored if the operator
/// enabled it; otherwise, the operator's prevails.
#[derive(Debug, Clone)]
pub enum SystemPolicy {
    /// System prompt set by the operator (default; not overridable by the caller).
    Operator(String),
    /// Envelope system prompt, accepted because the operator enabled it.
    CallerOverride(String),
}

impl SystemPolicy {
    /// Effective system-prompt text, regardless of the origin.
    ///
    /// The headless runner consumes it to populate `AgentRunConfig::system` (REQ-H12b) — the
    /// origin was already recorded in `AppliedCaps::system_override_applied` at the time of
    /// resolution.
    #[must_use]
    pub fn text(&self) -> &str {
        match self {
            Self::Operator(s) | Self::CallerOverride(s) => s,
        }
    }
}

// NOTE: `InputFormat` is defined in `input.rs` (parser-local, `pub` for the fuzz target), not
// here — it is a parser input, not part of the output contract. The former duplicate
// declaration in this module was removed.

#[cfg(test)]
mod tests {
    use super::*;
    use crate::magi::BudgetTelemetry;

    /// `#[serde(flatten)]` merges `BudgetTelemetry`'s keys into `AppliedCaps`'s own map. A name
    /// collision would silently drop one value: same map, second write wins, output still valid
    /// JSON, nothing errors. This is the only thing standing between that and a consumer reading a
    /// stale number.
    ///
    /// **How it detects a collision without a hand-written list:** the flattened map must contain
    /// every key the inner struct produces on its own, and its size must be the sum of both
    /// contributions. A collision makes the second write overwrite the first, so the total comes
    /// out one short — which is the assertion below, and it holds for field names nobody has
    /// written yet.
    ///
    /// **Mutation-verify it** (Step 4b, required): rename `BudgetTelemetry::ceiling_floored` to
    /// `timeout_secs` and this test must fail on the count. Restore it afterwards.
    #[test]
    fn the_flattened_budget_keeps_every_key_of_both_structs() {
        /// `AppliedCaps`' OWN serialized fields, excluding the flattened `budget`. The one value
        /// that must move by hand — and only when `AppliedCaps` itself gains or loses a field,
        /// never when `BudgetTelemetry` does.
        const APPLIED_CAPS_OWN_FIELDS: usize = 4;

        let budget = BudgetTelemetry::default();
        let inner = serde_json::to_value(budget).expect("BudgetTelemetry serializes");
        let inner_keys: std::collections::BTreeSet<String> = inner
            .as_object()
            .expect("a JSON object")
            .keys()
            .cloned()
            .collect();

        let caps = AppliedCaps {
            max_tool_calls: 15,
            max_tool_calls_clamped: false,
            timeout_secs: Some(1800),
            system_override_applied: false,
            budget,
        };
        let flat = serde_json::to_value(&caps).expect("AppliedCaps serializes");
        let flat_keys: std::collections::BTreeSet<String> = flat
            .as_object()
            .expect("a JSON object")
            .keys()
            .cloned()
            .collect();

        // 1. Flattened, not nested: every inner key is a sibling of the outer ones.
        let missing: Vec<&String> = inner_keys.difference(&flat_keys).collect();
        assert!(
            missing.is_empty(),
            "BudgetTelemetry keys absent from the flattened output: {missing:?}. Either the flatten \
             attribute is gone (they would be nested under \"budget\") or a name collides with one \
             of AppliedCaps' own fields and serde dropped it."
        );

        // 2. No collision: the flattened map is the SUM of both contributions. One short means
        //    two fields shared a name and the second write silently won.
        assert_eq!(
            flat_keys.len(),
            APPLIED_CAPS_OWN_FIELDS + inner_keys.len(),
            "flattened key count is not the sum of both structs' fields. If it is LOWER, the two \
             structs collide on a name and a value is being dropped silently — fix the collision, \
             never this assertion. If HIGHER, AppliedCaps gained a field: update \
             APPLIED_CAPS_OWN_FIELDS after checking BudgetTelemetry does not already use that name. \
             inner keys were: {inner_keys:?}"
        );
    }
}
