// Author: Julian Bolivar Version: 1.0.0 Date: 2026-07-18 Shared types of the headless output
// contract (MS1 ↔ MS2).
//!
//! DEFINED here, not referenced without definition — avoids the TDD-ordering build break (T6
//! uses `AppliedCaps` before T7 exists). The types are declared `pub` with their fields +
//! derives: T6 consumes [`AppliedCaps`]/[`SystemPolicy`]; T7 implements the formatting and
//! golden over [`RunOutcome`] and company. MS2
//! **fills** these types with the actual `Agent` output from the crate of the
//! binary, which can only reach the lib's `pub` API (not `pub(crate)`).
//!
//! The actual consumers of these types arrive in later tasks of the same milestone (T6/T7) and
//! in the binary runner (MS2).

use serde::Serialize;

/// Complete result of a headless run (`magi query`/`consult`).
///
/// It is the **stable** projection that the contract serializes (REQ-H14), decoupled from the
/// `Agent`'s internal `Message`: MS2 fills it, not redefines it.
#[derive(Debug, Clone, Serialize)]
pub struct RunOutcome {
    /// Agent response text; `None` if the run ended in error.
    pub response: Option<String>,
    /// Effective model used in the run.
    pub model: String,
    /// Effective provider used in the run.
    pub provider: String,
    /// Input/output token count (billing/observability).
    pub usage: Usage,
    /// Run latencies (total and, optionally, per turn).
    pub timings: Timings,
    /// Reason why the agent loop stopped.
    pub stop_reason: StopReason,
    /// Auditable record of each tool invocation.
    pub tool_calls: Vec<ToolCallRecord>,
    /// Normalized transcription by message (stable projection).
    pub transcript: Vec<TranscriptEntry>,
    /// Opaque MAGI object from a `consult` pass; `None` if there was none.
    pub consult: Option<serde_json::Value>,
    /// Effective limits after applying operator caps and envelope clamps.
    pub applied_caps: AppliedCaps,
    /// Error detail if the run failed; `None` on success.
    pub error: Option<ErrorPayload>,
}

/// Token count consumed by the run.
#[derive(Debug, Clone, Serialize)]
pub struct Usage {
    /// Input tokens (prompt + context + tool results).
    pub input_tokens: u64,
    /// Output tokens generated by the model.
    pub output_tokens: u64,
}

/// Latencies observed during the run.
#[derive(Debug, Clone, Serialize)]
pub struct Timings {
    /// Total duration of the run in milliseconds.
    pub total_ms: u64,
    /// Time-to-first-byte of the first token, if measured.
    pub ttfb_ms: Option<u64>,
    /// Duration of each loop turn, in order.
    pub per_turn_ms: Vec<u64>,
}

/// Reason why the agent loop stopped.
///
/// Priority when they co-occur (REQ-H14): `Error` > `MaxToolCalls` > `Denied` > `Done`.
/// Serializes as `snake_case` (stable contract).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum StopReason {
    /// The agent completed and produced its final response.
    Done,
    /// The tool invocation cap was reached.
    MaxToolCalls,
    /// An essential tool was denied by the tier and blocked the task.
    Denied,
    /// The run ended in error (includes timeout and repetitive guard).
    Error,
}

/// Auditable record of a single tool invocation.
#[derive(Debug, Clone, Serialize)]
pub struct ToolCallRecord {
    /// Name of the invoked tool.
    pub name: String,
    /// JSON input with which the tool was invoked.
    pub input: serde_json::Value,
    /// Tool result (truncated to `TOOL_RESULT_CAP` by the formatter).
    pub result: String,
    /// Duration of the invocation in milliseconds.
    pub ms: u64,
    /// `true` if the tool ran successfully; `false` if it failed or was denied.
    pub ok: bool,
}

/// One entry in the normalized transcript (one per message).
#[derive(Debug, Clone, Serialize)]
pub struct TranscriptEntry {
    /// Normalized message role (`assistant`/`user`/`tool`).
    pub role: String,
    /// Textual content of the message.
    pub content: String,
    /// Tool invocations associated with the message, if any.
    pub tool_calls: Option<Vec<ToolCallRecord>>,
}

/// Effective limits applied to the run (makes the REQ-H12b clamp visible).
#[derive(Debug, Clone, Serialize)]
pub struct AppliedCaps {
    /// Effective tool invocation cap after applying the operator cap.
    pub max_tool_calls: u32,
    /// `true` if the envelope's `max_tool_calls` was cut to the cap.
    pub max_tool_calls_clamped: bool,
    /// Wall-clock cap in seconds, if one was set.
    pub timeout_secs: Option<u64>,
    /// `true` if the envelope's `system` was applied (requires the operator flag).
    pub system_override_applied: bool,
}

/// Structured detail of a run error in the JSON output.
#[derive(Debug, Clone, Serialize)]
pub struct ErrorPayload {
    /// Safe message (already sanitized; never a raw secret).
    pub message: String,
    /// Error class, so the caller can route without parsing the message.
    pub kind: ErrorKind,
}

/// Error class of a headless run (maps 1:1 to an exit code, REQ-H14).
///
/// Serializes as `snake_case`. A new enum value is **additive** (REQ-H14): the consumer must
/// treat an unknown value as catch-all, not break.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ErrorKind {
    /// Invalid input / bad CLI usage (→ exit 2).
    InputInvalid,
    /// Corrupt DB: data present without envelope (→ exit 1, never-delete).
    DbCorrupt,
    /// Incorrect passphrase; retryable, never deletes (→ exit 1 in headless).
    WrongPassphrase,
    /// No passphrase and no TTY to ask for it (→ exit 1).
    PassphraseUnavailable,
    /// An essential tool was denied by the tier and blocked the task (→ exit 3).
    TierDenied,
    /// LLM provider failure (HTTP/network), with sanitized message (→ exit 1).
    Provider,
    /// The wall-clock `--timeout` expired (→ exit 1). First-class class.
    Timeout,
    /// Any other agent runtime error (→ exit 1).
    Runtime,
}

/// Effective system prompt of the run together with its **origin** (REQ-H12b).
///
/// The origin is a safety limit: the envelope's `system` is only honored if the operator
/// enabled it; otherwise, the operator's prevails.
#[derive(Debug, Clone)]
pub enum SystemPolicy {
    /// System prompt set by the operator (default; not overridable by the caller).
    Operator(String),
    /// Envelope system prompt, accepted because the operator enabled it.
    CallerOverride(String),
}

impl SystemPolicy {
    /// Effective system-prompt text, regardless of the origin.
    ///
    /// The headless runner consumes it to populate `AgentRunConfig::system` (REQ-H12b) — the
    /// origin was already recorded in `AppliedCaps::system_override_applied` at the time of
    /// resolution.
    #[must_use]
    pub fn text(&self) -> &str {
        match self {
            Self::Operator(s) | Self::CallerOverride(s) => s,
        }
    }
}

// NOTE: `InputFormat` is defined in `input.rs` (parser-local, `pub` for the fuzz target), not
// here — it is a parser input, not part of the output contract. The former duplicate
// declaration in this module was removed.
